- arguments: [-XCPP, --cpp-define=HLINT, --cpp-ansi]

- ignore:
    name: Use camelCase

- ignore:
    name: Use lambda-case

- ignore: {name: Hoist not, within: [Ersatz.Bit]} # This is how we define `any`, ya dingus
- ignore: {name: Use ||, within: [Ersatz.Relation.Prop]} # This is a different `or`
- ignore: {name: Use &&, within: [Ersatz.Relation.Prop]} # This is a different `and`
