language: c
sudo: false

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.3 GHCOPTS="" JOPTS="-j2"
      addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.3, minisat],sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.1 GHCOPTS="" JOPTS="-j2"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1, minisat],  sources: [hvr-ghc]}}

  allow_failures:
   - env: CABALVER=head GHCVER=head GHCOPTS="" JOPTS="-j2"

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - export CABAL=cabal-$CABALVER
 - $CABAL --version
 - travis_retry $CABAL update

install:
 - $CABAL install --constraint=transformers\ installed happy alex
 - export PATH=$HOME/.cabal/bin:$PATH
 - $CABAL install $JOPTS --enable-tests --only-dependencies --force

script:
 - $CABAL configure -v2 --enable-tests
 - $CABAL build $JOPTS --ghc-options=$GHCOPTS
 - |
   if [ $GHCVER != "head" ]; then
     $CABAL test
   fi

notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "\x0313ersatz\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
